"""updated application model

Revision ID: 62f30a0cbb3a
Revises: c7cfb28d58f3
Create Date: 2023-11-28 15:52:59.797514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f30a0cbb3a'
down_revision = 'c7cfb28d58f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fee_payment_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lors_request', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('lors_request')
        batch_op.drop_column('fee_payment_done')
        batch_op.drop_column('application_status')

    # ### end Alembic commands ###
